version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${NAME}
    container_name: api_Nest
    volumes:
      - ./postgres:/var/lib/postgresql/data